# Site settings
title: JackJohnKeller.com
email: jackjohnkeller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All things Jack Keller:  Front End Dev, Rugby, and dumb stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jackjohnkeller.com" # the base hostname & protocol for your site
twitter_username: j3kk3l
github_username:  jackeller

# Build settings
markdown: kramdown
